version: "3.8"

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: q-cards-db
    volumes:
      - ./data/db:/database
    networks:
      - default
      - mongo-express

  mongo_express:
    image: mongo-express:1.0.0-alpha.4 # イメージのバージョンも念のため指定
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin # mongo-expressアクセス時に要求されるユーザー名。なくてもOK。
      ME_CONFIG_BASICAUTH_PASSWORD: Password1 # mongo-expressアクセス時に要求されるパスワード。なくてもOK。
    depends_on:
      - mongo # mongoコンテナが起動してから起動させる
    networks:
      - mongo-express

  app:
    image: node:16 # 今回はExpressフレームワークを動かしたかったのでNode.js
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    working_dir: /app
    command: "yarn start"
    depends_on:
      - mongo
    networks:
      - default

networks:
  default:
    driver: bridge
  mongo-express:
    driver: bridge
